export const ADD_SUBTOPIC = "ADD_SUBTOPIC";
export const REMOVE_SUBTOPIC = "REMOVE_SUBTOPIC";
export const CHANGE_NUM_QUESTIONS = "CHANGE_NUM_QUESTIONS";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const SET_LOADING = "SET_LOADING";

export const GET_DATA = "GET_DATA";
